Message:
  Title: "&b[Minecraft 言語パック] "
  Data_Re_read: "データを再読み込み中..."
  Data_Re_read_Complete: "データの読み込みが完了しました"

Timer:
  TimeStart: "&a%time% 秒以内に入力を完了してください!"
  TimeOut: "&c %time% 秒が経過しました"
  TimeLeft:
    - "&c残り %%10%% 秒で入力できます"
    - "&c残り %%5%% 秒で入力できます"
    - "&c残り %%4%% 秒で入力できます"
    - "&c残り %%3%% 秒で入力できます"
    - "&c残り %%2%% 秒で入力できます"
    - "&c残り %%1%% 秒で入力できます"

Command:
  CmdCanNotUse: "&cコンソールではこのコマンドは使用できません"
  PlayerCanNotUse: "&cこのコマンドは使用できません"
  NoPermission: "&cこのコマンドを使用する権限がありません"
  CanNotFind: "&cコマンドが見つかりません"
  HandNoItem: "&c手にアイテムがありません"
  ItemNotFind: "&cアイテムが見つかりません"

LoadMinecraftLang:
  Title: "&b[LoadMinecraftLang] "
  SetLang: "&eMinecraftの言語を設定しました: &a%lang%"
  SetVersionPath: "&eMinecraftのバージョンを設定しました: &a%versionPath%"
  GetLangFileName: "&e言語ファイル名を取得しました: &a%fileName%"
  Load_LangItems: "&e言語パックが読み込まれました: &a%count%"
  Load_MinecraftOriginItem: "&eMinecraftのオリジナルアイテムが読み込まれました: &a%count%"
  Internet_TryToDownload: "&e公式から言語パックのダウンロードを試みています: &a%fileName%"
  Internet_DownloadSuccess: "&e言語パックのダウンロードが完了しました"
  Error_LangNotFound: "&c言語パックが見つかりません: &a%fileName%"
