################
# Set language #
################
lang: en

########################
# Web API and UI panel #
########################
web:
  enabled: false
  host: 127.0.0.1
  port: 8765
  cors: true
  maxEntriesPerRequest: 300
  api:
    host: 127.0.0.1
    port: 8765
    cors: true
    maxEntriesPerRequest: 300
  frontend:
    enabled: true
    host: 127.0.0.1
    port: 8766
    staticDir: web
