name: MCLang
main: org.tsob.MCLang.Main
version: ${full.version}
author: 0obrino0
website: github.com/0obriano0/MCLang
description: Lightweight API to load and use official Minecraft language pack translations.
api-version: 1.13
folia-supported: true
libraries:
  - com.fasterxml.jackson.core:jackson-databind:2.17.1
commands:
  mclang:
    description: mclang Commands.
permissions:
  mclang.*:
    default: op
    description: Give players with op everything by default
    children:
      mclang.user.*: true
      mclang.admin.*: true
  mclang.user.*:
    default: true
    children:
      mclang.user: true
      mclang.user.help: true
  mclang.admin.*:
    default: op
    children:
      mclang.admin: true
      mclang.admin.reload: true
      mclang.admin.test: true
      mclang.admin.path: true
      mclang.admin.update.notify: true