Message:
  Title: "&b[Minecraft 語言包] "
  Data_Re_read: "重新讀取資料..."
  Data_Re_read_Complete: "資料讀取完成"

Timer:
  TimeStart: "&a請於 %time% 秒內完成輸入!"
  TimeOut: "&c %time% 秒的時間已到"
  TimeLeft:
    - "&c還剩餘 %%10%% 秒能輸入"
    - "&c還剩餘  %%5%% 秒能輸入"
    - "&c還剩餘  %%4%% 秒能輸入"
    - "&c還剩餘  %%3%% 秒能輸入"
    - "&c還剩餘  %%2%% 秒能輸入"
    - "&c還剩餘  %%1%% 秒能輸入"

Command:
  CmdCanNotUse: "&c後台無法使用此指令"
  PlayerCanNotUse: "&c無法使用此指令"
  NoPermission: "&c無使用此指令的權限"
  CanNotFind: "&c查無此指令"
  HandNoItem: "&c手上沒有物品"
  ItemNotFind: "&c查無此物品"

LoadMinecraftLang:
  Title: "&b[LoadMinecraftLang] "
  SetLang: "&e設定 Minecraft 語言為: &a%lang%"
  SetVersionPath: "&e設定 Minecraft 版本為: &a%versionPath%"
  GetLangFileName: "&e取得語言檔案名稱: &a%fileName%"
  Load_LangItems: "&e語言包已載入: &a%count%"
  Load_MinecraftOriginItem: "&eMinecraft 原版物品已載入: &a%count%"
  Internet_TryToDownload: "&e嘗試從官方下載語言包: &a%fileName%"
  Internet_DownloadSuccess: "&e語言包下載完成"
  Error_LangNotFound: "&c語言包未找到: &a%fileName%"
