name: Build Test

on:
  push:
    
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build all modules (root pom)
        run: mvn -B package

      - name: Show project structure for debug
        run: tree -L 2

      - name: List finish folder for debug
        run: ls -lh finish