name: Build and Release MCLang-Antrun

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build all modules (root pom)
        run: mvn -B package

      - name: Show project structure for debug
        run: tree -L 2

      - name: List finish folder for debug
        run: ls -lh finish

      - name: Upload JAR to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: finish/*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}