name: Build and Publish core Javadoc to GitHub Pages & Releases

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy-javadoc:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Generate core Javadoc
        run: mvn -B -pl core javadoc:javadoc

      - name: List core javadoc output (for debug)
        run: ls -lR core/target/reports/apidocs

      - name: Compress core javadoc
        run: |
          cd core/target/reports
          zip -r ../../../core-javadoc.zip apidocs

      - name: Deploy core Javadoc to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./core/target/reports/apidocs

      - name: Upload Javadoc ZIP to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: core-javadoc.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}