name: Build and Publish API Javadoc to GitHub Pages & Releases

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy-javadoc:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      # 主要修改在此：安裝整個專案（含 root pom 與所有模組）
      - name: Build and install all modules (install to local repo)
        run: mvn -B install -Dgpg.skip

      - name: Generate MCLang-API Javadoc
        run: mvn -B -pl MCLang-API javadoc:javadoc -Dgpg.skip

      - name: List MCLang-API javadoc output (for debug)
        run: ls -lR MCLang-API/target/site/apidocs

      - name: Compress MCLang-API javadoc
        run: |
          cd MCLang-API/target/site
          zip -r ../../../MCLang-API-javadoc.zip apidocs

      - name: Deploy MCLang-API Javadoc to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./MCLang-API/target/site/apidocs

      - name: Upload Javadoc ZIP to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: MCLang-API-javadoc.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}