name: Build and Publish core Javadoc to GitHub Pages

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy-javadoc:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Build dependencies (optional)
        run: mvn -B package -DskipTests

      - name: Generate core Javadoc
        run: mvn -B -pl core javadoc:javadoc

      - name: Deploy core Javadoc to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./core/target/site/apidocs
          # 可自訂發布路徑，例如 docs/core-vX.Y.Z
          # publish_branch: gh-pages
          # destination_dir: core-javadoc
